# Generated by Django 3.2.8 on 2021-11-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_commissions', '0002_auto_20211103_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='financing',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='year',
        ),
        migrations.AddField(
            model_name='organization',
            name='accounts_payable_in_the_current_period',
            field=models.BigIntegerField(null=True, verbose_name='Объем кредиторской  задолженности текущего периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='accounts_payable_in_the_previous_period',
            field=models.BigIntegerField(null=True, verbose_name='Объем кредиторской  задолженности прошлого периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='actual_date_at_the_end_of_the_reporting_period',
            field=models.DateField(null=True, verbose_name='Фактическая дата на конец отчетного периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='amount_of_identified_financial_violations',
            field=models.BigIntegerField(null=True, verbose_name='Объем выявленных финансовых нарушений'),
        ),
        migrations.AddField(
            model_name='organization',
            name='amount_of_receivables_of_the_current_period',
            field=models.BigIntegerField(null=True, verbose_name='Объем дебиторской задолженности текущего периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='annual_funding_of_the_institution',
            field=models.BigIntegerField(null=True, verbose_name='Годовой объем финансирования учреждения'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cash_expense',
            field=models.BigIntegerField(null=True, verbose_name='Кассовый расход(исполнение плаченных обязательств по бюджетным программам (подпрограммам)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='date_of_the_last_check',
            field=models.DateField(null=True, verbose_name='Дата проведения последней проверки'),
        ),
        migrations.AddField(
            model_name='organization',
            name='financing_volume_at_the_end_of_the_financial_year',
            field=models.BigIntegerField(null=True, verbose_name='Объем финансирования на конец финансового года'),
        ),
        migrations.AddField(
            model_name='organization',
            name='funding_volume_of_the_current_period',
            field=models.BigIntegerField(null=True, verbose_name='Объем финансирования текущего периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='funding_volume_of_the_previous_period',
            field=models.BigIntegerField(null=True, verbose_name='Объем финансирования прошлого периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='period_since_the_last_governmental_audit',
            field=models.DateField(null=True, verbose_name='Срок с момента проведения последнего государственного аудита'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stability_of_accountants_in_the_institution_over_the_past_period',
            field=models.IntegerField(null=True, verbose_name='Стабильность бухгалтеров в учреждении за прошлый период'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volume_of_receivables_from_the_previous_period',
            field=models.BigIntegerField(null=True, verbose_name='Объем дебиторской задолженности прошлого периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volume_of_recovered_reimbursed_funds',
            field=models.BigIntegerField(null=True, verbose_name='Объем востановленных/возмещенных средств'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volume_of_violations_of_public_procurement',
            field=models.BigIntegerField(null=True, verbose_name='Объем нарушений по гос.закупкам'),
        ),
    ]
