# Generated by Django 3.2.8 on 2021-11-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_commissions', '0003_auto_20211105_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='period_since_the_last_governmental_audit',
            field=models.IntegerField(null=True, verbose_name='Срок с момента проведения последнего государственного аудита'),
        ),
    ]
