# Generated by Django 3.2.8 on 2021-11-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision_commissions', '0004_alter_organization_period_since_the_last_governmental_audit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='annual_funding_of_the_institution',
            new_name='annualFunding',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='cash_expense',
            new_name='cashExpense',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='date_of_the_last_check',
            new_name='dateLastCheck',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='actual_date_at_the_end_of_the_reporting_period',
            new_name='dateReport',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='funding_volume_of_the_current_period',
            new_name='finCurPeriod',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='financing_volume_at_the_end_of_the_financial_year',
            new_name='finEndYear',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='funding_volume_of_the_previous_period',
            new_name='finPrePeriod',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='amount_of_identified_financial_violations',
            new_name='finViolations',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='accounts_payable_in_the_current_period',
            new_name='payableCurrent',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='accounts_payable_in_the_previous_period',
            new_name='payablePrevious',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='period_since_the_last_governmental_audit',
            new_name='perLastAudit',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='stability_of_accountants_in_the_institution_over_the_past_period',
            new_name='stableAccountants',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='volume_of_violations_of_public_procurement',
            new_name='violationProc',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='amount_of_receivables_of_the_current_period',
            new_name='volReceivableCurrent',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='volume_of_receivables_from_the_previous_period',
            new_name='volReceivablePrevious',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='volume_of_recovered_reimbursed_funds',
            new_name='volRecoverFin',
        ),
    ]
