# Generated by Django 3.2.8 on 2021-11-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revision_commissions', '0005_auto_20211106_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='perLastAudit',
            new_name='preLastAudit',
        ),
    ]
