# Generated by Django 3.2.9 on 2021-11-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_commissions', '0006_rename_perlastaudit_organization_prelastaudit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='stableAccountants',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='violationProc',
        ),
        migrations.AddField(
            model_name='organization',
            name='administrativeMeasures',
            field=models.IntegerField(null=True, verbose_name='Административные меры в результате выявленных нарушений по государственным закупкам'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cashExpenseCurrent',
            field=models.BigIntegerField(null=True, verbose_name='Кассовый расход (исполнение оплаченных обязательств по бюджетным программам (подпрограммам)) текущего периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='disciplineMeasures',
            field=models.IntegerField(null=True, verbose_name='Дисциплинарные меры в результате выявленных нарушений по государственным закупкам'),
        ),
        migrations.AddField(
            model_name='organization',
            name='disciplineSanctions',
            field=models.IntegerField(null=True, verbose_name='Дисциплинарные взыскания, дискредитирующие государственную службу'),
        ),
        migrations.AddField(
            model_name='organization',
            name='employeeEthics',
            field=models.IntegerField(null=True, verbose_name='Количество сотрудников, привлеченных к дисциплинарной ответственности советом по этике'),
        ),
        migrations.AddField(
            model_name='organization',
            name='firedViolation',
            field=models.IntegerField(null=True, verbose_name='Увольнение в результате выявленных нарушений по государственным закупкам'),
        ),
        migrations.AddField(
            model_name='organization',
            name='illegalActions',
            field=models.IntegerField(null=True, verbose_name='Коррупционные и уголовные действия при освоении бюджетных средств'),
        ),
        migrations.AddField(
            model_name='organization',
            name='materialEthics',
            field=models.IntegerField(null=True, verbose_name='Количество материалов рассмотренных советом по этике'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volAdministrativeSpendings',
            field=models.IntegerField(null=True, verbose_name='Объем административных расходов текущего периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volAuthorizedCapitalCurrent',
            field=models.IntegerField(null=True, verbose_name='Объем уставного капитала текущего периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volAuthorizedCapitalPrevious',
            field=models.IntegerField(null=True, verbose_name='Объем уставного капитала прошлого периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volDividentsCurrent',
            field=models.IntegerField(null=True, verbose_name='Объем дивидендов текущего периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volIncomeCurrent',
            field=models.IntegerField(null=True, verbose_name='Объем чистой прибыли текущего периода'),
        ),
        migrations.AddField(
            model_name='organization',
            name='volIncomePrevious',
            field=models.IntegerField(null=True, verbose_name='Объем чистой прибыли прошлого периода'),
        ),
    ]
