# Generated by Django 3.2.9 on 2022-02-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revision_commissions', '0008_auto_20211201_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization_GU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование организации')),
                ('annualFunding', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Годовой объем финансирования учреждения')),
                ('finPrePeriod', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем финансирования прошлого периода')),
                ('finCurPeriod', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем финансирования текущего периода')),
                ('finEndYear', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем финансирования на конец финансового года')),
                ('cashExpense', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Кассовый расход(исполнение плаченных обязательств по бюджетным программам (подпрограммам)')),
                ('dateLastCheck', models.DateField(null=True, verbose_name='Дата проведения последней проверки')),
                ('dateReport', models.DateField(null=True, verbose_name='Фактическая дата на конец отчетного периода')),
                ('finViolations', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем выявленных финансовых нарушений')),
                ('volRecoverFin', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем востановленных/возмещенных средств')),
                ('volReceivableCurrent', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем дебиторской задолженности текущего периода')),
                ('volReceivablePrevious', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем дебиторской задолженности прошлого периода')),
                ('payableCurrent', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем кредиторской  задолженности текущего периода')),
                ('payablePrevious', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем кредиторской  задолженности прошлого периода')),
                ('illegalActions', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Коррупционные и уголовные действия при освоении бюджетных средств')),
                ('disciplineSanctions', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Дисциплинарные взыскания, дискредитирующие государственную службу')),
                ('materialEthics', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Количество материалов рассмотренных советом по этике')),
                ('employeeEthics', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Количество сотрудников, привлеченных к дисциплинарной ответственности советом по этике')),
                ('administrativeMeasures', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Административные меры в результате выявленных нарушений по государственным закупкам')),
                ('disciplineMeasures', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Дисциплинарные меры в результате выявленных нарушений по государственным закупкам')),
                ('firedViolation', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Увольнение в результате выявленных нарушений по государственным закупкам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'GU Organizations',
            },
        ),
        migrations.CreateModel(
            name='Organization_KVAZI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование организации')),
                ('annualFunding', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Годовой объем финансирования учреждения')),
                ('finEndYear', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем финансирования на конец финансового года')),
                ('cashExpense', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Кассовый расход(исполнение плаченных обязательств по бюджетным программам (подпрограммам)')),
                ('dateLastCheck', models.DateField(null=True, verbose_name='Дата проведения последней проверки')),
                ('dateReport', models.DateField(null=True, verbose_name='Фактическая дата на конец отчетного периода')),
                ('finViolations', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем выявленных финансовых нарушений')),
                ('volRecoverFin', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем востановленных/возмещенных средств')),
                ('volReceivableCurrent', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем дебиторской задолженности текущего периода')),
                ('volReceivablePrevious', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем дебиторской задолженности прошлого периода')),
                ('payableCurrent', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем кредиторской  задолженности текущего периода')),
                ('payablePrevious', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем кредиторской  задолженности прошлого периода')),
                ('illegalActions', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Коррупционные и уголовные действия при освоении бюджетных средств')),
                ('disciplineSanctions', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Дисциплинарные взыскания, дискредитирующие государственную службу')),
                ('employeeEthics', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Количество сотрудников, привлеченных к дисциплинарной ответственности советом по этике')),
                ('administrativeMeasures', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Административные меры в результате выявленных нарушений по государственным закупкам')),
                ('disciplineMeasures', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Дисциплинарные меры в результате выявленных нарушений по государственным закупкам')),
                ('firedViolation', models.PositiveIntegerField(help_text='Ед.', null=True, verbose_name='Увольнение в результате выявленных нарушений по государственным закупкам')),
                ('volAuthorizedCapitalCurrent', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем уставного капитала текущего периода')),
                ('volAuthorizedCapitalPrevious', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем уставного капитала прошлого периода')),
                ('volIncomeCurrent', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем чистой прибыли текущего периода')),
                ('volIncomePrevious', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем чистой прибыли прошлого периода')),
                ('volDividentsCurrent', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем дивидендов текущего периода')),
                ('volAdministrativeSpendings', models.DecimalField(decimal_places=3, help_text='Тыс.тг', max_digits=15, null=True, verbose_name='Объем административных расходов текущего периода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organizations KVAZI',
            },
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
