# Generated by Django 3.2.9 on 2022-04-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision_commissions', '0010_auto_20220208_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization_gu',
            name='risk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='organization_gu',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='organization_kvazi',
            name='risk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='organization_kvazi',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
